---
title: "Power lifters"
author: "Barnabás Buzás"
date: '2021 06 10 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
install.packages("ggpubr")
library(ggpubr)
library(sjPlot)
library(broom)
library(performance)
library(psych)
install.packages("see")
library(see)
```

```{r}
# Read the data

ipf_lifts <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-08/ipf_lifts.csv")
```

```{r}
# EDA 
str(ipf_lifts)
view(ipf_lifts)
summary(ipf_lifts)

#plots
#Best deadlift by age in weight class: 90+.
ipf_lifts %>% 
  filter(weight_class_kg == "90+") %>%
  ggplot(aes(x = age, y = best3deadlift_kg)) + 
  geom_point()

#Best deadlift by age colorized by weight class. 
ipf_lifts %>% 
  ggplot(aes(x = age, y = best3deadlift_kg, color = weight_class_kg)) + 
  geom_point()

#Number of event types
ipf_lifts %>% 
  ggplot(aes(x = event, y = 1)) + 
  geom_col()

# Women and men distribution
ipf_lifts %>%
  ggplot(aes(x = sex, y = 1)) + 
  geom_col()
```

```{r}
#H1: The correlation between weight and best bench is smaller among women than among men.

#Women lifters - bench press
women_lifters <- ipf_lifts %>%
  filter(sex == "F")
  
cor.test(women_lifters$bodyweight_kg, women_lifters$best3bench_kg, 
                    method = "pearson")

ggscatter(women_lifters, x = "bodyweight_kg", y = "best3bench_kg", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Bodyweight (kg)", ylab = "Best 3 benches (kg)")

#Men lifters - bench press

men_lifters <- ipf_lifts %>%
  filter(sex == "M")

cor.test(men_lifters$bodyweight_kg, men_lifters$best3bench_kg, 
                    method = "pearson")

ggscatter(men_lifters, x = "bodyweight_kg", y = "best3bench_kg", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Bodyweight (kg)", ylab = "Best 3 benches (kg)")
```

```{r}
# Is there a correlation between body weight and place?

# Women lifters - place: very weak negative correlation.
women_lifters_place <- women_lifters %>%
  filter(place != c("G", "DQ", "DD", "NS")) %>%
  mutate(place_num = as.numeric(place), na.rm = TRUE)

cor.test(women_lifters_place$bodyweight_kg, women_lifters_place$place_num, 
                    method = "pearson")
ggscatter(women_lifters_place, x = "bodyweight_kg", y = "place_num", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Bodyweight (kg)", ylab = "Place")

# Men lifters - place: very weak posititive correlation
men_lifters_place <- men_lifters %>%
  filter(place != c("G", "DQ", "DD", "NS")) %>%
  mutate(place_num = as.numeric(place), na.rm = TRUE)

cor.test(men_lifters_place$bodyweight_kg, men_lifters_place$place_num, 
                    method = "pearson")

ggscatter(men_lifters_place, x = "bodyweight_kg", y = "place_num", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Bodyweight (kg)", ylab = "Place")

```

```{r}
# Regression analysis - weight and best bench

#Women
women_weight_bench_model <- 
  glm(best3bench_kg ~ bodyweight_kg, data = women_lifters_place, family = "gaussian")

summary(women_weight_bench_model)

tidy_women_weight_bench_model <- tidy(women_weight_bench_model, conf.int = TRUE, exponentiate = TRUE)

check_model(women_weight_bench_model)

#Men
men_weight_bench_model <- 
  glm(best3bench_kg ~ bodyweight_kg, data = men_lifters_place, family = "gaussian")

summary(men_weight_bench_model)

tidy_men_weight_bench_model <- tidy(men_weight_bench_model, conf.int = TRUE, exponentiate = TRUE)

check_model(men_weight_bench_model)

```

```{r}
# Regression analysis: are best best bench and weight predict place? 

#Women
women_complex_model <- glm(place_num ~ bodyweight_kg + best3bench_kg, data = women_lifters_place, family = "gaussian")

summary(women_complex_model)

tidy_Women_complex_model <- tidy(women_complex_model, conf.int = TRUE, exponentiate = TRUE)

check_model(women_complex_model)

#Men
men_complex_model <- glm(place_num ~ bodyweight_kg + best3bench_kg, data = men_lifters_place, family = "gaussian")

summary(men_complex_model)

tidy_men_complex_model <- tidy(men_complex_model, conf.int = TRUE, exponentiate = TRUE)

check_model(men_complex_model)
```

